services:
  # Eclipse Mosquitto MQTT Broker
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:latest
    restart: always
    ports:
    - "${MOSQUITTO_PORT:-1883}:1883"
    configs:
    - source: mosquitto_config
      target: /mosquitto/config/mosquitto.conf
      uid: '1883'
      gid: '1883'
      mode: 0444
    healthcheck:
      test: ["CMD", "mosquitto_sub", "-h", "localhost", "-p", "1883", "-t", "$$SYS/broker/version", "-C", "1", "-W", "2", "-i", "docker-qhealthcheck"]
      interval: 30s
      timeout: 3s
      retries: 5
      start_period: 30s
      start_interval: 5s
    labels:
      dtp.description: >-
        Eclipse Mosquitto MQTT Broker
      dtp.category: dataingress
      dtp.urls.mqtt: mqtt://${DTP_HOST}:${MOSQUITTO_PORT}/

configs:
  mosquitto_config:
    content: |
      allow_anonymous true
      listener 1883 0.0.0.0
      protocol mqtt
