services:
  # PostgreSQL with TimescaleDB
  timescaledb:
    container_name: postgres-timescaledb
    image: timescale/timescaledb:latest-pg17
    restart: always
    ports:
    - "${POSTGRES_PORT:-5432}:5432"
    environment:
      POSTGRES_PASSWORD: ${PG_ADMIN_PASSWORD}
    volumes:
    - pgdata:/pgdata
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "dtp", "-d", "dtp"]
      interval: 30s
      timeout: 3s
      retries: 5
      start_period: 30s
      start_interval: 5s
    labels:
      dtp.description: >-
        PostgreSQL with TimescaleDB extension
      dtp.category: datastore
  phppgadmin:
    container_name: phppgadmin
    image: phppgadmin
    restart: always
    build:
      context: ./phppgadmin
      dockerfile: Dockerfile
    volumes:
    - ./phppgadmin/phppgadmin.conf:/etc/apache2/conf-available/phppgadmin.conf
    - ./phppgadmin/config.inc.php:/etc/phppgadmin/config.inc.php
    ports:
    - "${PHPPGADMIN_PORT:-8080}:80"
    depends_on:
      timescaledb:
        condition: service_healthy
        restart: true
    healthcheck:
      test: ["CMD", "curl", "-fsSLo", "/dev/null", "http://localhost/phppgadmin"]
      interval: 30s
      timeout: 3s
      retries: 5
      start_period: 30s
      start_interval: 5s
    labels:
      dtp.description: >-
        PhpPGAdmin web interface for PostgreSQL
      dtp.category: datastore
      dtp.urls.web: ${TAILSCALE_HOST}:${PHPPGADMIN_PORT}/phppgadmin/

volumes:
  pgdata:
