services:
  # PostgreSQL with TimescaleDB
  timescaledb:
    container_name: postgres-timescaledb
    image: timescale/timescaledb:latest-pg17
    restart: always
    ports:
    - "${POSTGRES_PORT:-5432}:5432"
    environment:
      POSTGRES_PASSWORD: ${PG_ADMIN_PASSWORD}
    volumes:
    - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "dtp", "-d", "dtp"]
      interval: 30s
      timeout: 3s
      retries: 5
      start_period: 30s
      start_interval: 5s
    labels:
      dtp.description: >-
        PostgreSQL with TimescaleDB extension
      dtp.category: datastore
  phppgadmin:
    container_name: phppgadmin
    image: yinchi/phppgadmin:latest
    restart: always
    build:
      context: ./phppgadmin
      dockerfile: Dockerfile
    configs:
    - source: phppgadmin_config
      target: /etc/phppgadmin/config.inc.php
      mode: 0444
    - source: apache_config
      target: /etc/apache2/conf-available/phppgadmin.conf
      mode: 0444
    ports:
    - "${PHPPGADMIN_PORT:-8080}:80"
    depends_on:
      timescaledb:
        condition: service_healthy
        restart: true
    healthcheck:
      test: ["CMD", "curl", "-fsSLo", "/dev/null", "http://localhost/phppgadmin"]
      interval: 30s
      timeout: 3s
      retries: 5
      start_period: 30s
      start_interval: 5s
    labels:
      dtp.description: >-
        PhpPGAdmin web interface for PostgreSQL
      dtp.category: datastore
      dtp.urls.web: ${DTP_HOST}:${PHPPGADMIN_PORT}/phppgadmin/

volumes:
  pgdata:

configs:
  phppgadmin_config:
    content: |
      <?php

        $$conf['servers'][0]['desc'] = 'PostgreSQL';
        $$conf['servers'][0]['host'] = 'timescaledb';
        $$conf['servers'][0]['port'] = 5432;

        // Minimum length users can set their password to.
        $$conf['min_password_length'] = 1;

        // Width of the left frame in pixels (object browser)
        $$conf['left_width'] = 200;

        // Which look & feel theme to use
        $$conf['theme'] = 'default';

        // See: https://github.com/phppgadmin/phppgadmin/blob/master/conf/config.inc.php-dist
        $$conf['servers'][0]['sslmode'] = 'allow';
        $$conf['servers'][0]['defaultdb'] = 'template1';
        $$conf['servers'][0]['pg_dump_path'] = '/usr/bin/pg_dump';
        $$conf['servers'][0]['pg_dumpall_path'] = '/usr/bin/pg_dumpall';
        $$conf['default_lang'] = 'auto';
        $$conf['extra_session_security'] = true;
        $$conf['autocomplete'] = 'default on';
        $$conf['extra_login_security'] = true;
        $$conf['owned_only'] = false;
        $$conf['show_comments'] = true;
        $$conf['show_advanced'] = false;
        $$conf['show_system'] = false;
        $$conf['show_oids'] = false;
        $$conf['max_rows'] = 30;
        $$conf['max_chars'] = 50;
        $$conf['use_xhtml_strict'] = false;
        $$conf['help_base'] = 'http://www.postgresql.org/docs/%s/interactive/';
        $$conf['ajax_refresh'] = 3;
        $$conf['plugins'] = array();

        /*****************************************
        * Don't modify anything below this line *
        *****************************************/

        $$conf['version'] = 19;

      ?>

  apache_config:
    content: |
      Alias /phppgadmin /usr/share/phppgadmin
      <Directory /usr/share/phppgadmin>
          Options Indexes FollowSymLinks
          AllowOverride None
          Require all granted
      </Directory>

      RedirectMatch ^/$$ /phppgadmin
