services:
  # PostgreSQL with TimescaleDB
  timescaledb:
    container_name: postgres-timescaledb
    image: timescale/timescaledb:latest-pg17
    ports:
    - "${POSTGRES_PORT:-5432}:5432"
    environment:
    - POSTGRES_PASSWORD=${PG_ADMIN_PASSWORD}
    volumes:
    - pgdata:/pgdata
  phppgadmin:
    container_name: phppgadmin
    image: phppgadmin
    build:
      context: ./phppgadmin
      dockerfile: Dockerfile
    volumes:
    - ./phppgadmin/phppgadmin.conf:/etc/apache2/conf-available/phppgadmin.conf
    - ./phppgadmin/config.inc.php:/etc/phppgadmin/config.inc.php
    ports:
    - "${PHPPGADMIN_PORT:-8080}:80"

volumes:
  pgdata:
