services:
  admin-api:
    container_name: admin-api
    image: ghcr.io/astral-sh/uv:python3.14-trixie
    volumes:
    - ../../admin_services/api:/app/admin_services/api
    - ../../py_common:/app/py_common
    - ../../LICENSE:/app/LICENSE
    - ../../pyproject.toml:/app/pyproject.toml
    - ../../README.md:/app/README.md
    - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      # --root-path setting for FastAPI
      DTP_ADMIN_API_ROOT_PATH: /api/admin
      # Database settings
      PG_HOSTNAME: timescaledb
      POSTGRES_PORT: ${POSTGRES_PORT}
      PG_USER: ${PG_USER}
      PG_USER_PASSWORD: ${PG_USER_PASSWORD}
      PG_DB: ${PG_DB}
    expose:
    - 8000
    command:
    - bash
    - "-c"
    - "cd /app && uv sync --all-packages && uv run admin-api"
    depends_on:
      timescaledb:
        condition: service_healthy
        restart: true
    healthcheck:
      test: ["CMD", "wget", "-qO", "/dev/null", "http://localhost:8000/health"]
      interval: 30s
      timeout: 3s
      retries: 5
      start_period: 30s
      start_interval: 5s
    labels:
      dtp.description: FastAPI server for admin functions
      dtp.category: admin_services
      dtp.urls.web: ${TAILSCALE_HOST}:${TRAEFIK_PORT}/api/admin
      traefik.enable: true
      traefik.http.routers.admin-api.rule: PathPrefix(`/api/admin`)
      traefik.http.routers.admin-api.middlewares: auth@file,admin-api-stripprefix
      traefik.http.middlewares.admin-api-stripprefix.stripprefix.prefixes: /api/admin
